### ISSUE TITLE
Create boiler-plate config for gRPC and protobufs

### ISSUE THREAD

**Issue by dpezely** [helium/helium-packet-router#10]
Create boiler-plate config for gRPC and protobufs for `helium-packet-router`:

- Configuration for gRPC and protobufs replicated from various other Helium repos:
  + e.g., blockchain-core, router, miner, sibyl
  + Followed Mack's excellent trail of breadcrumbs through those repos
- Since `helium-packet-router` is more "gateway" than "router", various tweaks were made to this instance of the config
- Primary differences from [router](https://github.com/helium/router/) are:
  + Behaviour here reuses `helium_router_bhvr`, of which its implementation in `router` was [recently updated](https://github.com/helium/router/pull/823)
  + Here, we'll just use that one rpc's `StateChannel` param as an envelope around `Packet`
  + Considered but ruled-out using `helium_gateway_bhvr` due to rpc end points not needed here
  + See [src/grpc/helium_packet_router_service.erl](https://github.com/helium/helium-packet-router/blob/dpezely/boilerplate-grpc-protobufs/src/grpc/helium_packet_router_service.erl)
- Notes regarding the Erlang "behaviour"
  + hpr doesn't need anything to do with state-channels
  + but some of that info already being sent by `gateway-rs` may be useful metadata or for logging
  + hpr probably should ignore (pass-through) anything region-specific
  + etc.  (please comment on this ticket if you can think of any others)
- See [PR#9](https://github.com/helium/helium-packet-router/pull/9)

**Comment by dpezely** [comment]
An Erlang `behaviour` as used here gets defined under [proto](https://github.com/helium/proto) repo:
- `helium_FOO_bhvr` would be specified in `helium/proto/src/service/FOO.proto` file
- Thus, for using `-behaviour(helium_gateway_bhvr)`, 
   see [proto/src/service/gateway.proto](https://github.com/helium/proto/blob/master/src/service/gateway.proto)
   section `service gateway { rpc ... }`

Exploring a new light-weight version of `gateway` behavior that omits state-channel methods, etc...

**Comment by madninja** [comment]
or just add to the gateway behavior and deprecate the older ones over time. Seriously
