### ISSUE TITLE
Add hotspot metadata in uplinks

### ISSUE THREAD

**Issue by lytzV** [helium/helium-packet-router#108]
We will need to add hotspot name in our uplinks & join accepts so that Chirpstack can display it in LoRaWAN frames & Events.

https://github.com/chirpstack/chirpstack-gateway-bridge/blob/master/internal/backend/semtechudp/packets/push_data.go#L345

**Comment by lytzV** [comment]
Will this mess up other UDP based ingestion if they don't parse for "meta"?

**Comment by macpie** [comment]
I don't think it should
