### ISSUE TITLE
Create Debian package for HPR

### ISSUE THREAD

**Issue by macpie** [helium/helium-packet-router#16]
See [PR#17](https://github.com/helium/helium-packet-router/pull/17)

Tasks:
- [x] construct Debian package `.deb` file based upon a successful `rebar3 release` run
   + Used `router` repo as placeholder: `rebar3 as testnet rel`;
   + See https://github.com/helium/router/pull/847
- [x] confirmed .deb generation against `router` repo; see Draft PR
- [x] authored `systemd` config and launch scripts (required)
- [x] authored `/etc/init/` and `/etc/rc?.d/` launch scripts
- [x] authored `Dockerfile` for testing within a pristine container
- [x] authored `Vagrantfile` for testing within a pristine VM
- [x] confirmed .deb extraction within clean Docker image
- [x] confirmed .deb extraction within clean Vagrant VM
- [ ] confirmed successful deploy of .deb within clean container
   + Blocked on Helium packet-router `main` branch having successful `make rel`
- [ ] confirmed successful deploy of .deb within clean VM
   + Blocked on Helium packet-router `main` branch having successful `make rel`

Future efforts:

- Local repo for storage until accepted into a Debian repo
- Successful submission to official Debian repo
   + For a rough idea of Debian package submission complexity: 
      https://www.debian.org/doc/manuals/packaging-tutorial/packaging-tutorial.en.pdf#Outline0.6.1.42

OUTDATED sketch:

Debian packages can be generated via `Makefile`, and here's a generic version that just needs to be confirmed against current `man` pages and refined:

```Makefile
# Excerpt for Makefile to build .deb package

# FIXME: don't use var in this way.  this is just to highlight it in this draft:
MAIN_THING=helium-packet-router

RELEASE=0.1.0
PACKAGE_BUILD=`date +%Y%m%d.%H%M%S`
REVISION=${RELEASE}-${PACKAGE_BUILD}
DEBIAN_PACKAGE_NAME=helium-packet-router

DESTDIR=/opt/hpr

RUNTIME_USER=nobody

package: package-bin package-cfg


# FIXME: change names of .sh scripts
release: ${MAIN_THING}
	rm -rf release
	mkdir -p release${DESTDIR}/{bin,var/{log,run}}
	cp -p ${MAIN_THING}{,.ini,.sh} release${DESTDIR}/bin/

# FIXME: update to accommodate systemd
package-bin: release
	mkdir -p release/DEBIAN
	find release -type d | xargs chmod 755
	sed "s/Version: 1.0-1/Version: ${REVISION}/" < deb-bin-control.txt | sed "s/Architecture: all/Architecture: `dpkg --print-architecture`/" > release/DEBIAN/control
	svn info | egrep 'URL|Revision' | sed 's/^/ /' >> release/DEBIAN/control
	echo "#! /bin/sh" > release/DEBIAN/postinst
	echo 'chown -R `((id ${RUNTIME_USER} >/dev/null && echo ${RUNTIME_USER}:${RUNTIME_USER})|| echo nobody:nogroup)`' ${DESTDIR}/ >> release/DEBIAN/postinst
	echo "ln -s ${DESTDIR}/bin/${MAIN_THING}.sh /etc/init.d/" >> release/DEBIAN/postinst
	echo "ln -s ${DESTDIR}/bin/${MAIN_THING}.sh /etc/rc3.d/S40${MAIN_THING}" >> release/DEBIAN/postinst
	echo "ln -s ${DESTDIR}/bin/${MAIN_THING}.sh /etc/rc1.d/K40${MAIN_THING}" >> release/DEBIAN/postinst
	echo "echo To manually start, use:" >> release/DEBIAN/postinst
	echo "echo su - ${RUNTIME_USER} ${DESTDIR}/bin/${MAIN_THING}.sh start" >> release/DEBIAN/postinst
	echo "#! /bin/sh" > release/DEBIAN/prerm
	echo "${DESTDIR}/bin/${MAIN_THING}.sh stop" >> release/DEBIAN/prerm
	echo "${DESTDIR}/bin/${MAIN_THING}.sh unkind-stop" >> release/DEBIAN/prerm
	echo "${DESTDIR}/bin/${MAIN_THING}.sh clean-logs" >> release/DEBIAN/prerm
	echo "rm -f ${DESTDIR}/var/run/scoreboard.txt*" >> release/DEBIAN/prerm
	echo "rm -f ${DESTDIR}/var/log/console.log.[A-Z]*" >> release/DEBIAN/prerm
	echo "rm -f /etc/init.d/${MAIN_THING}.sh" >> release/DEBIAN/prerm
	echo "rm -f /etc/rc?.d/*${MAIN_THING}" >> release/DEBIAN/prerm
	chmod 755 release/DEBIAN/{postinst,prerm}
	dpkg-deb --build release
	mv release.deb ${DEBIAN_PACKAGE_NAME}-bin_${REVISION}_`arch`.deb
	ls -lh *.deb

package-cfg: ${MAIN_THING}_${RELEASE}.ini
	mkdir -p release-config/DEBIAN
	mkdir -p release-config${DESTDIR}/bin/
	find release-config -type d | xargs chmod 755
	cp -p ${MAIN_THING}_${RELEASE}.ini release-config${DESTDIR}/bin/${MAIN_THING}.ini
	sed "s/Version: 1.0-1/Version: ${REVISION}/" < deb-cfg-control.txt > release-config/DEBIAN/control
	svn info | egrep 'URL|Revision' | sed 's/^/ /' >> release/DEBIAN/control
	echo "#! /bin/sh" > release-config/DEBIAN/postinst
	echo "${DESTDIR}/bin/${MAIN_THING}.sh reload-config" >> release-config/DEBIAN/postinst
	chmod 755 release-config/DEBIAN/postinst
	dpkg-deb --build release-config
	mv release-config.deb ${DEBIAN_PACKAGE_NAME}-cfg-DEL_${REVISION}.deb
	ls -lh *.deb

clean:
	rm -rf release release-config *.deb
```

**Comment by dpezely** [comment]
@jontow Do you have preferences for Debian package parameters, such as:
- Separate .deb files for binaries versus config of each environment?
  + i.e., isolate config of each environment (prod, vip, staging, dev) to its own .deb package?
- Destination directory; e.g.,
    + ` /opt/<app_name>` as is currently used by `WORKDIR` in `Dockerfile`, or
    + `/usr/local/<app_name>` or
    + `/usr/local/{bin,etc,...}/<app_name>`
- include vs ignore pre-systemd init scripts under `/etc/rc?.d/` and `/etc/init.d/`
   + Community members might appreciate these being included
- Username for runtime of `router` and `helium-packet-router`?

Sample Makefile template is in ticket description, from which I'll update/confirm against https://wiki.debian.org/Packaging and then build upon for our new .deb package.  That example uses a separate .deb package for config.

**Comment by jontow** [comment]
We aren't separating configuration into additional packages for anything else, but it's an interesting idea.  Might need some thought, but I think it's worth trying or at least debating in more depth.  The use case that I can see is a separate base package for "-mainnet", "-testnet", "-devnet", etc, but I also see the allure of prod, vip, staging, dev as currently used.  Additional packages for this are addtional maintenance, vs. distributing well-commented examples and instead putting configuration into something like ansible, so we'll want to weigh that burden carefully.

Destination directory: we've been leaning toward /opt/<app_name> for others, so should probably continue down that road unless we have good reason to change.

I've no problems including non-systemd init script examples in the packages: indeed, open source users may very much appreciate it, but if we don't have means of testing them regularly, we'll just have to call them examples.  I'm not sure which distributions are using .deb as their package format but not systemd at this point, but there are bound to be some.

We've been using `helium` as the service user for other packages, could certainly keep that convention for now.
