### ISSUE TITLE
Add devaddr_hash to iot-packet-ingest

### ISSUE THREAD

**Issue by mikev** [helium/helium-packet-router#187]
LoRaWAN Metrics provide important tracking data for business, engineering and product.  The active device count is arguably even more important than the daily DC burn or daily data transfer bytes because it measures the count of of physical LoRa sensors, e.g. it is more important to know how many temperature sensors are deployed and not how many temperature readings are taken per day.

We currently have no method of measuring the daily active device counts.

In order to properly determine active device counts we must measure the unique DevAddr counts per day.  Note - DevAddr can be multiplexed to multiple sensor devices, therefore ideally the devaddr_hash is constructed so it is unique per sensor.

I propose a unique Uint64 Hash composed of the DevAddr, OUI, Region, any other uniques attributes and optionally a unique per Epoch HPR Secret.    This allows counting unique DevAddrs but does not publicly expose the DevAddr.

This should be added to packet_router_packet_report_v1 as uint64 devaddr_hash.

**Comment by michaeldjeffrey** [comment]
Devaddrs don't correlate enough to devices to act as a way to count the number of devices using the network.
