### ISSUE TITLE
Eu868 packet routing

### ISSUE THREAD

**Issue by ccall48** [helium/helium-packet-router#253]
Join packets from devices added to our route id for eu868 devices never arrive on our chirp gwmp gw bridge hosted in australia our oui is 327.

Is there any way to run some kind of a route trace to check this?

I have double checked the port and gwmp mapping for eu868, doubled checked the bridge is running for that band and the firewall is open and port accessible externally.

**Comment by shawaj** [comment]
@ccall48 did you get this resolved? As we have it working

**Comment by ccall48** [comment]
> @ccall48 did you get this resolved? As we have it working

yeh I did, there was a hard to spot typo in the config file (my mistake).
