### ISSUE TITLE
roaming on dataonly hotspots

### ISSUE THREAD

**Issue by tomtobback** [helium/helium-packet-router#31]
Hi, i was using Senet devices roaming on a data-only hotspot: it stopped working in June, confirmed by Helium staff [here](https://github.com/helium/gateway-rs/issues/261#issuecomment-1165487354). any plans to enable roaming again? please advise if i should post elsewhere, thanks.

**Comment by michaeldjeffrey** [comment]
This repo is not deployed yet, and will have no bearing on the roaming ability of a data-only hotspot. 

In the original issue, the grpc endpoint for roaming servers was disabled, this is no longer the case.
