### ISSUE TITLE
HTTP roaming support

### ISSUE THREAD

**Issue by ruttenberg** [helium/helium-packet-router#48]
Support routing of packets to roaming partners via HTTP.
Passive routing only will be supported, based on the function and implementation of roaming in Packet Purchaser.

**Comment by ruttenberg** [comment]
@macpie @michaeldjeffrey 

Here are some questions that have arisen while migrating the packet purchaser roaming code:

1. How do we map from hpr_route:route() [#packet_router_route_v1_pb{}]  to the devaddr or eui that is expected in the uplink payload?

2. The downlink packet created by PP  is a #packet_pb{}. The downlink packet used by HPR is a #packet_router_packet_down_v1_pb{}, which does not support all of the information in #packet_pb(). How should this be handled?

4. The PP code handles a "No Roaming Agreement" by calling pp_config:stop_buying/1. Is there some analogous action in HPR?

5. The PP code uses window_pb{}, which has a datarate field whose type is unicode:chardata(). The corresponding structure in HPR is window_v1_pb{}, which also has a datarate field, but its values are an enum, represented by a fixed set of atoms ('SF12BW125' | 'SF11BW125' | 'SF10BW125' |...). It is not clear how pp_lorawan:index_to_datarate/2 can be adapted to work with the new datarate type.

6. PP gets gateway location information from the ledger and uses it to put latitude/longitude  information into the uplink payload. This location information is not available in the #packet_router_packet_up_v1_pb{} that provides the uplink to HPR.

**Comment by macpie** [comment]
1. The `hpr_route`only gives you routing informations. Look at [`hpr_routing:deliver_packet/3`](https://github.com/helium/helium-packet-router/blob/main/src/hpr_routing.erl#L66).
2. They should be comparable, what is missing there?
3.  There will be at some point but not right now
4. Gonna have to look at this one.
5. Yes this might have to be gone for now, as long as we get the pub key of the hotspot you can go find location info anyway.

**Comment by ruttenberg** [comment]
@macpie 
1. I will look at deliver_packet/3.
2. #packet_pb{} has a signal_strength field. #packet_router_packet_down_v1_pb{} does not.
