### ISSUE TITLE
GRPC packet ingestion

### ISSUE THREAD

**Issue by macpie** [helium/helium-packet-router#5]
Helium gateways speak gRPC to Helium LoRaWAN Network Servers (LNS)

- [x] #10
  + GitHub-CI is successful with grpc builds
- [x] Define new protobuf:  (Thanks, Pierre!)  See [packet_router.proto](https://github.com/helium/proto/blob/macpie/packet_router/src/service/packet_router.proto) in https://github.com/helium/proto/pull/157
- [x] Listen for inbound gRPC connections (https://github.com/helium/helium-packet-router/pull/25)

EDIT: unnecessary former tasks or accommodated through other means:
- Tee raw gRPC traffic to local file:
  + Required as an input to our Packet Verify service (lives outside of HPR or LNS)
  + Accommodates replaying traffic for debugging
  + Accommodates live traffic going to next Release Candidate but with all safeguards of Production environment
- Forward to `router` as gRPC (https://github.com/helium/helium-packet-router/pull/30)
- Accommodate load-balancer sessions with id/token in gRPC values or headers

Notes:

- Inbound traffic from gateway-rs will be gRPC flowing through a load-balancer
   + AWS app layer ELB is gRPC aware
- Handling of large scale traffic volumes will be deferred to load-balancer
   + e.g., Let LB maintain large socket listen queue because setup/shutdown of sockets from LB to packet-router across AWS backbone should be relatively cheap
   + Therefore, nothing special to be done for tuning Linux kernel or Erlang/BEAM
- This ticket is just for the Listening portion of gRPC
   + The companion use of `http2_client` for accommodating sending to Class C devices (downlink without an uplink initiating the request) will be implemented as a separate effort

**Comment by macpie** [comment]
This should probably be split up

**Comment by dpezely** [comment]
> This should probably be split up

Updated description with task list / TODO items.  We can further break out items as needed later.

**Comment by dpezely** [comment]
Where `router` used its own Erlang behavior, `helium_router_bhvr`,
packet-router functions more like yet another intermediate gateway.
Therefore, its behavior will be `gateway_bhvr` in terms of gRPC's autogen components.

**Comment by michaeldjeffrey** [comment]
This branch https://github.com/helium/helium-packet-router/pull/25 and this branch https://github.com/helium/helium-packet-router/pull/27 both accept packets over grpc when running a local gateway-rs on this branch https://github.com/helium/gateway-rs/pull/289.

To get gateway-rs working, comment out the `[[routers]]` in `default.toml` and add your version of packet-router as a `[[router]]`.

**Comment by dpezely** [comment]
Recommend just closing this ticket:

The preliminary work done for this ticket was superseded by the fine craftsmanship of others on HPR when I was down for the count with massive headaches over a couple of days.

While there might be no specific tests yet that would have been created per this ticket, there will be sufficient code coverage out of necessity for those other features.
