### ISSUE TITLE
MIC Benchmark

### ISSUE THREAD

**Issue by macpie** [helium/helium-packet-router#87]
We need to know an approximate limit on how many "MIC  brute forcing" we can do before seeing a significant slow down.

[Here](https://github.com/helium/router/blob/master/src/device/router_device_routing.erl#L1211) is the Router code that does the MIC calculation.

**Comment by marcsugiyama** [comment]
From what I can tell, the rate at which we can compare MIC is going to be limited by the rate we can call crypto:macN/5. The rest of the code seems to be fairly straightforward binary manipulation. The crypto function is backed by a NIF. Does this seem right, or am I missing something?

Measuring:
```
crypto:macN(cmac, aes_128_cbc, <<"0123456789abcdef">>, <<"12345678901234567890123">>, 4)
```
on a M1 Macbook gives about 1 microsec per call.

```
-module(crypto_test).

-export([main/1]).

main(Count) ->
    {MicroSecs, _} = timer:tc(fun() -> run_test(Count) end),
    io:format("~p~n", [MicroSecs/Count]).

run_test(Count) ->
    run_test(<<"0123456789abcdef">>, <<"123456789012345678901234">>, Count).

run_test(_, _, 0) ->
    ok;
run_test(Key, Body, Count) ->
    crypto:macN(cmac, aes_128_cbc, Key, Body, 4),
    run_test(Key, Body, Count - 1).
```
In erl:
```
2> crypto_test:main(1_000_000).
1.077096
ok
3> crypto_test:main(10_000_000).
1.0232326
ok
```
